name: KendariKids CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # Setup Node.js v18 (without cache: pnpm!)
      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # --- SERVER CACHE & CHECKS ---
      - name: Cache Server pnpm modules
        uses: actions/cache@v3
        with:
          path: ./server/node_modules
          key: ${{ runner.os }}-pnpm-server-${{ hashFiles('server/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-server-

      - name: Install Server Dependencies
        run: pnpm install
        working-directory: ./server

      - name: Run Server Lint Check
        run: pnpm run lint
        working-directory: ./server

      # --- CLIENT CACHE & CHECKS ---
      - name: Cache Client pnpm modules
        uses: actions/cache@v3
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-pnpm-client-${{ hashFiles('client/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-client-

      - name: Install Client Dependencies
        run: pnpm install
        working-directory: ./client

      - name: Run Client Lint Check
        run: pnpm run lint
        working-directory: ./client

      - name: Build Client for Production
        run: pnpm run build
        working-directory: ./client
