# .github/workflows/ci.yml

name: KendariKids CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # CHANGE 1: Use the official pnpm/action-setup action to install pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Use a recent version of pnpm

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # CHANGE 2: Tell the cache to use pnpm's lock file
          cache: 'pnpm'

      # --- SERVER CHECKS ---
      
      # CHANGE 3: Use 'pnpm install' instead of 'npm install'
      - name: Install Server Dependencies
        run: pnpm install
        working-directory: ./server

      - name: Run Server Lint Check
        run: pnpm run lint
        working-directory: ./server
          
      # --- CLIENT CHECKS ---
      
      - name: Install Client Dependencies
        run: pnpm install
        working-directory: ./client
        
      - name: Run Client Lint Check
        run: pnpm run lint
        working-directory: ./client
          
      - name: Build Client for Production
        run: pnpm run build
        working-directory: ./client